# utils/ai_integration.py
"""
D-ID Video Avatar Integration for EDAPTIV
Creates personalized video teachers using your custom avatar images
"""

import os
import time
import requests
from typing import Dict, Optional


class DIDVideoGenerator:
    """
    D-ID API Integration for generating avatar videos
    Uses your custom Google Drive avatar images for each subject
    """
    
    def __init__(self):
        self.api_key = os.environ.get('DID_API_KEY')
        self.base_url = "https://api.d-id.com"
        
        if not self.api_key:
            raise ValueError("D-ID API key not found in environment variables")
    
    def get_headers(self):
        """Return headers for D-ID API requests"""
        return {
            "accept": "application/json",
            "content-type": "application/json",
            "authorization": f"Basic {self.api_key}"
        }
    
    def get_avatar_url(self, subject: str) -> str:
        """
        Get Google Drive avatar image URL for the subject
        
        ADD YOUR GOOGLE DRIVE LINKS HERE!
        Format: https://drive.google.com/uc?export=view&id=https://drive.google.com/uc?export=view&id=11YwJb-tc_xoC3GizVSxhCbNb91yEwEui/view?usp=drive_link
        
        To get the file ID from a Google Drive link:
        Original: https://drive.google.com/file/d/11YwJb-tc_xoC3GizVSxhCbNb91yEwEui/view?usp=sharing
        File ID: 11YwJb-tc_xoC3GizVSxhCbNb91yEwEui
        Direct link: https://drive.google.com/uc?export=view&id=11YwJb-tc_xoC3GizVSxhCbNb91yEwEui
        """
        
        # Your custom avatar URLs for each subject   
        AVATAR_URLS = {
            'mathematics': 'https://drive.google.com/uc?export=download&id=1Sw-H3Dy1kGUmqKCugHSfHA_r9Tt1E_Ap',
            'science': 'https://drive.google.com/uc?export=download&id=1Sw-H3Dy1kGUmqKCugHSfHA_r9Tt1E_Ap',
            'english': 'https://drive.google.com/uc?export=download&id=1Sw-H3Dy1kGUmqKCugHSfHA_r9Tt1E_Ap',
            'social studies': 'https://drive.google.com/uc?export=download&id=1Sw-H3Dy1kGUmqKCugHSfHA_r9Tt1E_Ap',
            'art': 'https://drive.google.com/uc?export=download&id=1Sw-H3Dy1kGUmqKCugHSfHA_r9Tt1E_Ap',
            'physical education': 'https://drive.google.com/uc?export=download&id=1Sw-H3Dy1kGUmqKCugHSfHA_r9Tt1E_Ap',
            
            # Default avatar (if subject not found)
            'default': 'https://drive.google.com/uc?export=download&id=1Sw-H3Dy1kGUmqKCugHSfHA_r9Tt1E_Ap'
        }
        
        # Get avatar URL for subject (case-insensitive)
        avatar_url = AVATAR_URLS.get(subject.lower(), AVATAR_URLS['default'])
        
        return avatar_url
    
    def select_voice_for_primary_school(self, subject: str) -> str:
        """
        Select appropriate voice for primary school students
        Uses warm, friendly, age-appropriate voices
        
        Args:
            subject: Subject area
        
        Returns:
            Voice ID string for Microsoft Azure TTS
        """
        
        # Primary school friendly voices (warm, clear, engaging)
        PRIMARY_VOICES = {
            'mathematics': 'en-US-NancyNeural',      
            'science': 'en-US-NancyNeural',          
            'english': 'en-US-NancyNeural',         
            'social studies': 'en-US-NancyNeural',
            'art': 'en-US-NancyNeural',              
            'computer': 'en-US-NancyNeural',  
            'default': 'en-US-NancyNeural'           
        }
        
        return PRIMARY_VOICES.get(subject.lower(), PRIMARY_VOICES['default'])
    
    def create_video(
        self, 
        script: str,
        subject: str,
        student_name: str = "friend"
    ) -> Dict:
        """
        Create a talking avatar video from the teaching script
        
        Args:
            script: The teaching script generated by DeepSeek R1
            subject: Subject area (to select appropriate avatar)
            student_name: Student's name (for logging/tracking)
        
        Returns:
            Dictionary with:
            - success: bool
            - video_url: str (URL to the generated video)
            - talk_id: str (D-ID video ID)
            - duration: float (video length in seconds)
            - error: str (if failed)
        """
        
        # Get avatar image for this subject
        avatar_url = self.get_avatar_url(subject)
        
        # Get appropriate voice for primary school
        voice_id = self.select_voice_for_primary_school(subject)
        
        # Limit script length (D-ID has limits)
        if len(script) > 3000:
            print(f"⚠️ Script too long ({len(script)} chars), truncating to 3000")
            script = script[:3000] + "..."
        
        # Prepare request payload
        payload = {
            "source_url": avatar_url,
            "script": {
                "type": "text",
                "input": script,
                "provider": {
                    "type": "microsoft",
                    "voice_id": "en-US-NancyNeural"
                },
                "ssml": False  # Using plain text, not SSML
            },
            "config": {
                "stitch": True,      # Smooth video transitions
                "fluent": True,      # Natural speech flow
                "pad_audio": 2,      # Two seconds padding
                "driver_expressions": {
                    "expressions": {
                        "start_frame": 0, 
                        "expression": "happy",
                        "blink": 0.5,
                        "neutral": 0.5

                        }
                    
                }
            }
        }
        
        print(f"🎬 Creating video for {student_name}...")
        print(f"📚 Subject: {subject}")
        print(f"🎙️ Voice: {voice_id}")
        print(f"👤 Avatar: {avatar_url[:50]}...")
        print(f"📝 Script length: {len(script)} characters")
        
        try:
            # Step 1: Create the video (submit job)
            response = requests.post(
                f"{self.base_url}/talks/{talk_id}",
                json=payload,
                headers=self.get_headers()
            )
            response.raise_for_status()
            
            result = response.json()
            talk_id = result.get('id')
            
            if not talk_id:
                raise Exception("No talk ID received from D-ID")
            
            print(f"✅ Video job created! ID: {talk_id}")
            print(f"⏳ Generating video (this takes 60-120 seconds)...")
            
            # Step 2: Wait for video to be ready
            video_url = self.wait_for_video(talk_id)
            
            if video_url:
                print(f"🎉 Video ready! URL: {video_url[:50]}...")
                
                return {
                    'success': True,
                    'video_url': video_url,
                    'talk_id': talk_id,
                    'duration': result.get('duration', 0),
                    'avatar_used': avatar_url,
                    'voice_used': voice_id
                }
            else:
                raise Exception("Video generation failed or timed out")
            
        except requests.exceptions.RequestException as e:
            error_msg = f"D-ID API error: {str(e)}"
            print(f"❌ {error_msg}")
            
            # Try to get more detailed error
            try:
                error_detail = response.json()
                error_msg += f" - {error_detail}"
            except:
                pass
            
            return {
                'success': False,
                'error': error_msg,
                'video_url': None,
                'talk_id': None
            }
        except Exception as e:
            error_msg = f"Video creation error: {str(e)}"
            print(f"❌ {error_msg}")
            return {
                'success': False,
                'error': error_msg,
                'video_url': None,
                'talk_id': None
            }
    
    def wait_for_video(self, talk_id: str, max_wait: int = 180) -> Optional[str]:
        """
        Poll D-ID API until video is ready
        
        Args:
            talk_id: The talk/video ID from create request
            max_wait: Maximum seconds to wait (default 3 minutes)
        
        Returns:
            Video URL when ready, or None if timeout
        """
        
        start_time = time.time()
        poll_interval = 3  # Check every 3 seconds
        last_status = None
        same_status_duration = 0
        max_stuck_time = 60  # Max time to stay in same status

        while time.time() - start_time < max_wait:
            try:
                response = requests.get(
                    f"{self.base_url}/talks/{talk_id}",
                    headers=self.get_headers()
                )
                response.raise_for_status()
                
                result = response.json()
                status = result.get('status')
                
                elapsed = int(time.time() - start_time)
                print(f"⏱️ Status: {status} (elapsed: {elapsed}s)")
                
                if status == 'done':
                    print("✅ Video ready!")
                    return result.get('result_url')
                elif status == 'error':
                    error_detail = result.get('error', 'Unknown error')
                    raise Exception(f"Video generation failed: {error_detail}")
                elif status == last_status:
                    same_status_duration += poll_interval
                    if same_status_duration >= max_stuck_time:
                        raise TimeoutError(f"⛔ Stuck at '{status}' for {same_status_duration}s — stopping.")
                    time.sleep(poll_interval)    
                elif status in ['created', 'started']:
                    # Still processing
                    time.sleep(poll_interval)
                else:
                    print(f"⚠️ Unknown status: {status}")
                    time.sleep(poll_interval)
                
            except Exception as e:
                print(f"❌ Error polling video status: {e}")
                return None
            
            except requests.exceptions.RequestException as e:
                print(f"❌ D-ID API polling error: {e}")
                return None
        
        # Timeout
        print(f"⏰ Video generation timed out after {max_wait} seconds")
        return None
    
    def get_video_info(self, talk_id: str) -> Dict:
        """
        Get information about a generated video
        
        Args:
            talk_id: The talk/video ID
        
        Returns:
            Dictionary with video information
        """
        try:
            response = requests.get(
                f"{self.base_url}/talks/{talk_id}",
                headers=self.get_headers()
            )
            response.raise_for_status()
            return response.json()
        except Exception as e:
            return {'error': str(e)}
    
    # def delete_video(self, talk_id: str) -> bool:
    #     """
    #     Delete a video from D-ID (to save storage)
        
    #     Args:
    #         talk_id: The talk/video ID to delete
        
    #     Returns:
    #         True if successful, False otherwise
    #     """
    #     try:
    #         response = requests.delete(
    #             f"{self.base_url}/talks/{talk_id}",
    #             headers=self.get_headers()
    #         )
    #         response.raise_for_status()
    #         print(f"🗑️ Video {talk_id} deleted successfully")
    #         return True
    #     except Exception as e:
    #         print(f"❌ Error deleting video: {e}")
    #         return False


def estimate_video_cost(script_length: int) -> dict:
    """
    Estimate cost for video generation based on D-ID Build plan
    
    Args:
        script_length: Number of characters in script
    
    Returns:
        Dictionary with time and cost estimates
    """
    
    # Average speaking rate: 150 words per minute
    # Average word length: 5 characters
    words = script_length / 5
    minutes = words / 150
    
    # D-ID Build plan: $18/month for 32 minutes = $0.5625 per minute
    cost_per_minute = 18 / 32
    
    # Round up to nearest 15 seconds (D-ID billing)
    rounded_minutes = ((minutes * 4) + 1) // 1 * 0.25
    
    estimated_cost = rounded_minutes * cost_per_minute
    
    return {
        'script_length': script_length,
        'estimated_words': int(words),
        'estimated_minutes': round(minutes, 2),
        'rounded_minutes': round(rounded_minutes, 2),
        'estimated_cost': round(estimated_cost, 2),
        'generation_time': '60-120 seconds'
    }


def test_did_connection():
    """
    Test D-ID API connection
    
    Returns:
        Boolean indicating if connection is successful
    """
    try:
        did = DIDVideoGenerator()
        
        # Simple test request - just list talks
        response = requests.get(
            f"{did.base_url}/talks",
            headers=did.get_headers(),
            params={'limit': 1}
        )
        
        if response.status_code == 200:
            print("✅ D-ID API connection successful!")
            print(f"📊 API Key is valid")
            return True
        else:
            print(f"❌ D-ID API error: {response.status_code}")
            print(f"Response: {response.text}")
            return False
            
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
        return False


# Example usage in your views:
"""
from utils.deepseek_integration import adapt_content_for_student
from utils.ai_integration import DIDVideoGenerator

# Step 1: Adapt content with DeepSeek R1
deepseek_result = adapt_content_for_student(
    material=material,
    learning_styles=student.learning_styles.all(),
    challenges=student.challenges.all(),
    student=student
)

if deepseek_result['success']:
    teaching_script = deepseek_result['teaching_script']
    
    # Step 2: Create video with D-ID using that script
    did = DIDVideoGenerator()
    video_result = did.create_video(
        script=teaching_script,
        subject=material.subject,
        student_name=student.user.first_name
    )
    
    if video_result['success']:
        video_url = video_result['video_url']
        # Save to database, show to student
"""