# Generated by Django 5.2.7 on 2025-11-06 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_institution_teacherprofile_students_user_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='code',
        ),
        migrations.AddField(
            model_name='adaptedcontent',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adapted_content', to='learning.institution'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique institution id', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(),
        ),
    ]
