# Generated by Django 5.2.7 on 2025-11-07 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_institution_code_adaptedcontent_institutuion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('social_studies', 'Social Studies'), ('compuer', 'Computer'), ('art', 'Art'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='learning.institution')),
                ('students', models.ManyToManyField(blank=True, related_name='class_groups', to='learning.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.classgroup'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.classgroup'),
        ),
    ]
