# Generated by Django 5.2.7 on 2025-11-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_studymaterial_subject_classgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_code',
            field=models.CharField(blank=True, help_text='Unique Institution code (e.g. TECH2024)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='learning.institution'),
        ),
    ]
