# Generated by Django 5.2.7 on 2025-11-12 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_institution_institution_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_active_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Trial'), ('small', 'Small (<100 students)'), ('medium', 'Medium (100-500 students)'), ('large', 'Large (500-1000 students)'), ('enterprise', 'Enterprise (1000+ students)')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('institution_admin', 'Institution Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='InstitutionAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('can_manage_teachers', models.BooleanField(default=True)),
                ('can_manage_students', models.BooleanField(default=True)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='learning.institution')),
            ],
        ),
    ]
