# Generated by Django 5.2.7 on 2025-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_institution_email_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=255, unique=True),
        ),
    ]
