# Generated by Django 5.2.7 on 2025-11-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, unique=True, max_length=255),
        ),
    ]
