# Generated by Django 5.2.7 on 2025-11-13 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20251113_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptedcontent',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
