# Generated by Django 5.2.7 on 2025-11-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_adaptedcontent_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptedcontent',
            name='video_duration',
            field=models.FloatField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='adaptedcontent',
            name='video_error_message',
            field=models.TextField(blank=True, help_text='Error if video generation failed', null=True),
        ),
        migrations.AddField(
            model_name='adaptedcontent',
            name='video_generated_at',
            field=models.DateTimeField(blank=True, help_text='When video was generated', null=True),
        ),
        migrations.AddField(
            model_name='adaptedcontent',
            name='video_generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adaptedcontent',
            name='video_talk_id',
            field=models.CharField(blank=True, help_text='D-ID talk ID for reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adaptedcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='D-ID generated video URL', max_length=500, null=True),
        ),
    ]
