# Generated by Django 5.2.7 on 2025-11-28 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_adaptedcontent_video_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptedcontent',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
