# Generated by Django 5.2.7 on 2025-11-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_adaptedcontent_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='institution_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='institution_code',
            field=models.CharField(default='TECH2024', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='institution_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to='learning.teacherprofile'),
        ),
    ]
