# Generated by Django 5.2.7 on 2025-12-01 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_studentprofile_institution_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='institution_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='institution_code',
            field=models.CharField(max_length=50),
        ),
    ]
