# Generated by Django 5.2.7 on 2025-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_studentprofile_institution_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='institution_code',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
