# Generated by Django 5.2.7 on 2025-12-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_alter_adaptedcontent_id_alter_assessment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Permanent video file storage', null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='Temporary D-ID URL (will expire)', max_length=500)),
                ('talk_id', models.CharField(blank=True, help_text='D-ID talk ID for reference', max_length=100)),
                ('avatar_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0, help_text='Video duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adapted_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_videos', to='learning.adaptedcontent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
