# Generated by Django 5.2.7 on 2025-12-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_alter_adaptedcontent_id_alter_assessment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptedcontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='adaptedcontent',
            name='video_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
